### ISSUE TITLE
Popup with likes creates horizontal scroll

### ISSUE THREAD

**Issue by fetsh** [clbn/freefeed-gamma#3]
Popup with likes to comment appears partly outside of the viewport and creates horizontal scroll.

![screenshot_20181003-115510](https://user-images.githubusercontent.com/14053/46406843-8f774880-c715-11e8-8aa3-4c88210719d7.png)

**Comment by clbn** [comment]
Thanks for reporting. When I introduced this tooltip I had to make a custom version of lib (or rather two libs) because the original one(s) had this bug. Unfortunately, it seems the bug reappeared a couple of months back, and somehow it's not always reproducible.

Anyway, I'm migrating the tooltip to the other library/version(s) these days, hopefully the bug will be gone.

I'll keep this issue open until then.

**Comment by clbn** [comment]
@fetsh A new tooltip implementation is now in production, and this must be fixed since the version `2019.02.09`. Could you please use it for a couple of days to confirm this is not happening anymore? (Please check the version in the page footer to make sure you have a newer one.)

**Comment by fetsh** [comment]
Can confirm, it's not happening anymore. Thanks!
